export interface ServiceData {
  slug: string;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  icon: string; // SVG shape type
  tag?: string;
  seo: {
    title: string;
    description: string;
    keywords: string[];
    aeoQuestion: string;
  };
  heroImage: string;
  whoFor: string[];
  requirements: {
    label: string;
    value: string;
  }[];
  pros: string[];
  cons: string[];
  process: {
    step: string;
    title: string;
    desc: string;
  }[];
  faqs: {
    q: string;
    a: string;
  }[];
}

export const services: ServiceData[] = [
  {
    slug: "purchase",
    name: "Purchase Loans",
    shortName: "Purchase",
    tagline: "Most home loans are simpler than they feel. We'll walk you through yours and get it closed.",
    description: "A purchase loan is the mortgage you use to buy a home. The Lindley Team at Movement Mortgage helps you find the right loan structure for your income, credit profile, down payment, and long-term financial goals. Whether you're a first-time buyer in Portland's Sellwood neighborhood or upgrading to a larger home in Lake Oswego, the purchase process starts with understanding where you are financially and where you want to go.",
    icon: "circle",
    tag: "Most Popular",
    seo: {
      title: "Portland Purchase Mortgage Loans | The Lindley Team",
      description: "Get pre-approved for a Portland home purchase with The Lindley Team at Movement Mortgage. Licensed in OR & WA. NMLS #1367416 / #265974.",
      keywords: ["Portland mortgage", "Oregon home loan", "Portland home purchase", "first time home buyer Portland", "mortgage lender Portland OR"],
      aeoQuestion: "How do I get a mortgage to buy a home in Portland Oregon?",
    },
    heroImage: "/img/home-buy.webp",
    whoFor: [
      "First-time home buyers entering the Portland market",
      "Move-up buyers upgrading to a larger home",
      "Relocating professionals moving to Oregon or Washington",
      "Real estate investors purchasing rental properties",
      "Buyers with non-traditional income (self-employed, 1099, commission-based)",
    ],
    requirements: [
      { label: "Credit Score", value: "580+ (FHA) or 620+ (Conventional)" },
      { label: "Down Payment", value: "As low as 0% (VA) or 3% (Conventional)" },
      { label: "DTI Ratio", value: "Typically under 45-50%" },
      { label: "Employment", value: "2 years history preferred" },
      { label: "Documentation", value: "Pay stubs, W2s/tax returns, bank statements" },
    ],
    pros: [
      "Build equity instead of paying rent",
      "Lock in fixed housing costs with a fixed-rate mortgage",
      "Tax benefits including mortgage interest deduction",
      "Access to a full range of loan programs through Movement Mortgage — matched to your situation",
      "Personalized strategy from an experienced Portland lender",
    ],
    cons: [
      "Requires upfront costs (down payment, closing costs)",
      "Market fluctuations can affect short-term home value",
      "Maintenance and property taxes are your responsibility",
      "Less flexibility than renting if your plans change quickly",
    ],
    process: [
      { step: "01", title: "Discovery Call", desc: "30-minute conversation about your goals, timeline, budget, and financial picture. No commitment, no pressure." },
      { step: "02", title: "Pre-Approval", desc: "We pull credit and verify income — you'll have a real answer within 24-48 hours. If you qualify, that's a pre-approval letter sellers take seriously." },
      { step: "03", title: "Loan Selection", desc: "Once you're under contract, we match you to the right program and structure it around your goals — with real room to move on pricing." },
      { step: "04", title: "Close & Keys", desc: "We manage the paperwork, coordinate with your agent and title company, and get you to the closing table on time." },
    ],
    faqs: [
      { q: "How much do I need for a down payment in Portland?", a: "Down payment requirements range from 0% (VA loans) to 3% (Conventional) to 3.5% (FHA). While 20% avoids private mortgage insurance (PMI), most Portland buyers put down far less. Oregon also has down payment assistance programs like OHCS that can help cover your upfront costs. We'll walk you through all your options." },
      { q: "How long does the mortgage process take?", a: "From pre-approval to closing, the typical timeline is 30-45 days. We can usually give you a real answer on pre-approval within 24-48 hours of getting your documents — approval itself depends on credit, income, and underwriting. The biggest variable after that is finding the right home; once you're under contract, we move fast." },
      { q: "What credit score do I need to buy a home?", a: "The minimum depends on the loan type: 580 for FHA, 620 for most Conventional loans, and no minimum for VA (though most lenders look for 580+). If your score is below these thresholds, we can discuss strategies to improve it before applying." },
      { q: "Should I get pre-approved before house hunting?", a: "Absolutely. In Portland's market, sellers expect buyers to have pre-approval letters. Without one, most listing agents won't take your offer seriously. Pre-approval also tells YOU what you can afford so you're not wasting time looking at homes outside your range." },
      { q: "Do I work with a person or a call center?", a: "A person — David or Bri, start to finish. No 1-800 queue. You get a full shelf of in-house loan programs and real room on pricing, so it's personal service and competitive terms, not one product getting pushed on you." },
      { q: "How much house can I afford in Portland?", a: "This depends on your income, debts, down payment, and the current interest rate. A general rule: your total monthly housing payment (mortgage + taxes + insurance) shouldn't exceed about 28-31% of your gross monthly income. Our calculator can give you a more specific number." },
      { q: "What are closing costs and how much should I expect?", a: "Closing costs typically run 2-5% of the home's purchase price. In Portland, on a $500,000 home, that's $10,000-$25,000. These include lender fees, title insurance, appraisal, prepaid taxes and insurance. We can sometimes negotiate seller credits to offset these." },
      { q: "Can I buy a home if I'm self-employed?", a: "Yes. Self-employed borrowers need 2 years of tax returns instead of W2s, and we use your net income (not gross). It can be trickier, but we work with self-employed buyers regularly and know which lenders are most flexible with non-traditional income." },
    ],
  },
  {
    slug: "refinance",
    name: "Refinance",
    shortName: "Refinance",
    tagline: "Refinancing only pays off sometimes. Run your numbers with us and we'll tell you if this is one of them.",
    description: "Refinancing replaces your current mortgage with a new one, ideally on better terms. The most common reasons: locking in a lower interest rate, switching from an adjustable-rate to a fixed-rate mortgage, shortening your loan term (e.g., 30-year to 15-year), or removing PMI once you've built 20% equity. But refinancing isn't always the right move — it comes with closing costs that need to be weighed against your savings. That's where we come in. We'll run the numbers honestly and tell you whether refinancing makes financial sense for your specific situation, even if the answer is 'not right now.'",
    icon: "square",
    seo: {
      title: "Portland Mortgage Refinance | The Lindley Team",
      description: "Should you refinance your Portland mortgage? We'll run the numbers and tell you honestly — no refi that doesn't pay for itself. Movement Mortgage programs, licensed OR & WA. NMLS #1367416.",
      keywords: ["Portland refinance", "Oregon mortgage refinance", "refinance rates Portland", "should I refinance my mortgage", "Portland refi"],
      aeoQuestion: "When should I refinance my mortgage in Oregon?",
    },
    heroImage: "/img/home-refinance.webp",
    whoFor: [
      "Homeowners with rates above current market rates",
      "Borrowers looking to drop PMI after gaining equity",
      "Homeowners wanting to switch from ARM to fixed-rate",
      "Those looking to shorten their loan term and save on interest",
      "Homeowners who want to consolidate debt at a lower rate",
    ],
    requirements: [
      { label: "Credit Score", value: "620+ (Conventional), 580+ (FHA Streamline)" },
      { label: "Equity", value: "Typically 5-20% depending on program" },
      { label: "DTI Ratio", value: "Under 50% in most cases" },
      { label: "Seasoning", value: "6-12 months since last refinance" },
      { label: "Documentation", value: "Pay stubs, W2s/tax returns, current mortgage statement" },
    ],
    pros: [
      "Lower monthly payment frees up cash flow",
      "Shorter term saves tens of thousands in interest over the life of the loan",
      "Fixed rate eliminates uncertainty of ARM adjustments",
      "Remove PMI once you've built sufficient equity",
      "Consolidate high-interest debt into a lower mortgage rate",
    ],
    cons: [
      "Closing costs typically 2-3% of loan amount",
      "Resets your amortization schedule if you extend the term",
      "Takes time to recoup costs (break-even analysis is critical)",
      "May not make sense if you plan to sell within 2-3 years",
    ],
    process: [
      { step: "01", title: "Break-Even Analysis", desc: "Before anything else, we calculate exactly how long it will take for your monthly savings to cover the closing costs. If the math doesn't work, we tell you." },
      { step: "02", title: "Rate Lock & Application", desc: "Once we confirm it makes sense, we lock your rate and start the application. We compare programs through Movement Mortgage to find the best terms for your situation." },
      { step: "03", title: "Appraisal & Underwriting", desc: "Your home gets appraised to confirm current value. Underwriting reviews your financial profile. We manage both processes." },
      { step: "04", title: "Close & Savings Begin", desc: "You sign the new loan docs, and your new (lower) payment starts the following month. Total timeline: 3-5 weeks." },
    ],
    faqs: [
      { q: "When does refinancing make sense?", a: "The old rule of thumb was 'refinance if rates drop 1%+' but the real answer depends on your break-even point. If you can recoup closing costs within 2-3 years through lower payments, it's usually worth it. If you're planning to sell before the break-even point, it's probably not." },
      { q: "How much does it cost to refinance in Oregon?", a: "Closing costs for a refinance typically run 2-3% of the loan amount. On a $400,000 loan, that's $8,000-$12,000. Some of these costs can be rolled into the new loan, and we can sometimes find lender credits to offset them." },
      { q: "Can I refinance with bad credit?", a: "FHA Streamline refinances have more flexible credit requirements (580+) and don't always require a new appraisal. Conventional refinances typically need 620+. If your credit has dropped, we can discuss options or strategies to improve it first." },
      { q: "How long does a refinance take?", a: "Typically 3-5 weeks from application to closing. FHA Streamline refinances can be faster since they require less documentation." },
      { q: "Should I refinance to a 15-year mortgage?", a: "A 15-year mortgage saves a huge amount in total interest, but your monthly payment will be higher. We'll show you both scenarios side-by-side so you can see the tradeoff between monthly cash flow and long-term savings." },
      { q: "What is an FHA Streamline refinance?", a: "If you currently have an FHA loan, an FHA Streamline lets you refinance with minimal documentation, no appraisal in many cases, and reduced closing costs. It's one of the simpler ways to lower your rate, with less paperwork and lower closing costs than a full refinance." },
      { q: "Can I refinance if I'm underwater on my mortgage?", a: "It's harder but not impossible. Some programs allow refinancing up to 97% LTV (loan-to-value). If you owe more than your home is worth, let's talk about your specific situation — there may be options." },
      { q: "What's the difference between rate-and-term and cash-out refinance?", a: "Rate-and-term refinance changes your rate and/or loan term without taking cash out. Cash-out refinance lets you borrow more than you owe and take the difference as cash. They have different rates, requirements, and purposes. We cover cash-out refinancing on a separate page." },
    ],
  },
  {
    slug: "divorce-lending",
    name: "Divorce Lending",
    shortName: "Divorce Lending",
    tagline: "In a divorce, the mortgage decisions matter as much as the legal ones. Bri is one of the few Oregon CDLPs who works both sides of that math — so you come out with the house handled and your options intact.",
    description: "Divorce changes everything about your financial picture — including your mortgage. Who keeps the house? Can one spouse qualify alone? How does an equity buyout work? What happens to your credit? These questions need answers before the divorce decree is finalized, not after. As a Certified Divorce Lending Professional (CDLP®), Bri Lindley works alongside divorce attorneys, mediators, and financial planners to ensure mortgage-related decisions are made with full information. This isn't about selling you a loan — it's about making sure the settlement agreement is financially realistic and that both parties can actually execute the plan. CDLP® is a registered certification mark of the Divorce Lending Association.",
    icon: "triangle",
    tag: "Specialist",
    seo: {
      title: "Divorce Mortgage Specialist Portland | CDLP | The Lindley Team",
      description: "Certified Divorce Lending Professional in Portland OR. Equity buyouts, refinancing during divorce, qualification analysis. Protect your home and your future.",
      keywords: ["divorce mortgage Portland", "CDLP Portland Oregon", "divorce lending specialist", "equity buyout mortgage", "divorce refinance Oregon"],
      aeoQuestion: "How does a divorce affect my mortgage in Oregon?",
    },
    heroImage: "/img/home-divorce.webp",
    whoFor: [
      "Spouses going through divorce who want to keep the marital home",
      "Divorcing couples who need to understand equity buyout options",
      "Divorce attorneys who need mortgage analysis for settlement negotiations",
      "Mediators who want realistic financial scenarios for both parties",
      "Recently divorced individuals ready to purchase a new home",
    ],
    requirements: [
      { label: "Timing", value: "Can begin analysis before divorce is finalized" },
      { label: "Credit", value: "Varies by program — we assess both parties" },
      { label: "Income", value: "Must qualify on individual income post-divorce" },
      { label: "Documentation", value: "Divorce decree (or draft), financial disclosures, pay stubs, tax returns" },
      { label: "Equity", value: "Home appraisal needed for buyout calculations" },
    ],
    pros: [
      "CDLP certification means specialized knowledge most lenders don't have",
      "Prevents costly mistakes in settlement agreements",
      "Analyzes whether keeping the home is financially viable before you commit",
      "Works directly with your attorney and mediator",
      "Confidential, judgment-free process",
    ],
    cons: [
      "Qualifying on a single income is harder — realistic expectations are important",
      "Equity buyouts require refinancing, which has closing costs",
      "Emotional attachment to the home can cloud financial judgment (we'll be honest)",
      "Timeline depends on divorce proceedings, which can be unpredictable",
    ],
    process: [
      { step: "01", title: "Confidential Consultation", desc: "We start with a private conversation about your situation. No judgment, no pressure. We need to understand the full financial picture before making any recommendations." },
      { step: "02", title: "Mortgage Analysis", desc: "We analyze both parties' ability to qualify independently. This includes income, credit, debts, and equity position. We produce a Real Property Detail Report for your attorney." },
      { step: "03", title: "Settlement Support", desc: "We work with your legal team to ensure the mortgage-related terms of the settlement are realistic and executable. This prevents agreements that look good on paper but can't actually be funded." },
      { step: "04", title: "Execution", desc: "Once the divorce is finalized, we execute the mortgage plan — whether that's an equity buyout refinance, a new purchase, or both." },
    ],
    faqs: [
      { q: "What is a CDLP and why does it matter?", a: "A Certified Divorce Lending Professional (CDLP®) has specialized training in the intersection of mortgage lending and divorce proceedings. Most loan officers don't understand how divorce settlements, alimony, child support, and property division affect mortgage qualification. A CDLP® does — and can prevent costly mistakes that a regular lender would miss." },
      { q: "Can I keep the house in a divorce?", a: "Possibly — but it depends on whether you can qualify for the mortgage on your own income, afford the equity buyout payment to your spouse, and handle the ongoing costs of homeownership solo. We'll run the numbers honestly and tell you whether it's realistic." },
      { q: "How does an equity buyout work?", a: "In an equity buyout, one spouse refinances the mortgage into their name only and pays the other spouse their share of the equity. For example, if the home is worth $600,000 with a $300,000 mortgage, there's $300,000 in equity. Each spouse's share is $150,000. The keeping spouse would refinance for $450,000 ($300,000 existing mortgage + $150,000 buyout)." },
      { q: "Should I talk to a CDLP before or after my divorce is finalized?", a: "Before — ideally during the settlement negotiation phase. Too many people finalize divorce agreements with mortgage terms that can't actually be executed. Getting a CDLP involved early ensures the settlement is financially realistic." },
      { q: "Will divorce hurt my credit score?", a: "Divorce itself doesn't affect credit, but the financial disruption often does. Late payments on joint accounts, increased debt-to-income ratios, and closing joint accounts can all impact scores. We can help you understand the credit implications and plan accordingly." },
      { q: "Can I use alimony or child support as income to qualify?", a: "Yes, in most cases — if you can document that you'll receive it for at least 3 more years and that it's been consistently paid. We know exactly how different lenders treat these income sources." },
      { q: "What if my spouse won't cooperate with the refinance?", a: "The divorce decree can compel cooperation, but timing and logistics matter. We work with your attorney to ensure the decree includes specific, actionable mortgage language that protects you." },
      { q: "How long after divorce can I buy a new home?", a: "You can start the process immediately after the divorce is finalized. In some cases, we can even begin pre-approval during the divorce if the terms are clear enough. The key is having a finalized decree that shows your income, debts, and obligations clearly." },
    ],
  },
  {
    slug: "fha",
    name: "FHA Loans",
    shortName: "FHA",
    tagline: "Lower down payments, flexible credit requirements — the government-backed program that gets first-time buyers through the door.",
    description: "FHA loans are mortgages insured by the Federal Housing Administration, designed to make homeownership accessible to buyers who might not qualify for conventional financing. With down payments as low as 3.5% and credit score requirements starting at 580, FHA loans are one of the most popular programs for first-time home buyers in the Portland metro area.",
    icon: "star",
    seo: {
      title: "FHA Loans Portland Oregon | Low Down Payment | The Lindley Team",
      description: "FHA loans in Portland with 3.5% down and flexible credit requirements. Expert guidance for first-time buyers in Oregon and Washington. NMLS #1367416.",
      keywords: ["FHA loan Portland", "FHA mortgage Oregon", "first time buyer FHA Portland", "FHA requirements Oregon", "low down payment mortgage Portland"],
      aeoQuestion: "What are the FHA loan requirements in Oregon?",
    },
    heroImage: "/img/illustration-portland.webp",
    whoFor: [
      "First-time home buyers with limited savings",
      "Buyers with credit scores in the 580-680 range",
      "Borrowers recovering from past credit events",
      "Buyers who want to put less than 5% down",
    ],
    requirements: [
      { label: "Credit Score", value: "580+ for 3.5% down; 500-579 for 10% down" },
      { label: "Down Payment", value: "3.5% minimum" },
      { label: "DTI Ratio", value: "Up to 57% with compensating factors" },
      { label: "MIP", value: "Upfront (1.75%) + Annual (0.55%)" },
      { label: "Property", value: "Must be primary residence; FHA appraisal required" },
    ],
    pros: ["Low 3.5% down payment", "Credit scores as low as 580", "Seller can contribute up to 6% toward closing costs", "Assumable by future buyers"],
    cons: ["Mortgage Insurance Premium (MIP) for life of loan on most terms", "Property must meet FHA condition standards", "Loan limits apply ($517,500 in Portland metro 2024)", "Primary residence only — no investment properties"],
    process: [
      { step: "01", title: "Discovery Call", desc: "We review your credit, income, and savings to confirm FHA is the right fit vs. other low-down-payment options." },
      { step: "02", title: "Pre-Approval", desc: "Full pre-approval with FHA-specific underwriting. You'll have a letter ready for offers." },
      { step: "03", title: "FHA Appraisal", desc: "FHA appraisals are slightly stricter than conventional — we prep you for what inspectors look for." },
      { step: "04", title: "Close & Move In", desc: "We handle the FHA-specific paperwork and get you to the closing table." },
    ],
    faqs: [
      { q: "What credit score do I need for an FHA loan in Oregon?", a: "580 or higher for the standard 3.5% down payment. Scores between 500-579 can qualify with 10% down. Below 500 is not eligible for FHA." },
      { q: "How much is the FHA down payment?", a: "The minimum is 3.5% of the purchase price. On a $400,000 Portland home, that's $14,000. This can come from savings, gifts from family, or Oregon down payment assistance programs." },
      { q: "What is FHA mortgage insurance (MIP)?", a: "FHA charges an upfront MIP of 1.75% of the loan amount (rolled into the loan) plus an annual MIP of 0.55% paid monthly. On most FHA loans, MIP lasts the life of the loan unless you refinance to conventional." },
      { q: "Can I use an FHA loan for a condo in Portland?", a: "Yes, but the condo complex must be on the FHA-approved list. Not all Portland condos qualify. We can check eligibility before you make an offer." },
      { q: "What are FHA loan limits in Portland?", a: "FHA loan limits vary by county and are updated annually. We'll confirm the current limit for your target area during our initial conversation." },
      { q: "Can I buy a fixer-upper with an FHA loan?", a: "The standard FHA 203(b) loan requires the home to meet minimum condition standards. For fixer-uppers, the FHA 203(k) renovation loan lets you finance both the purchase and renovations in one mortgage." },
    ],
  },
  {
    slug: "va",
    name: "VA Loans",
    shortName: "VA Loans",
    tagline: "Zero down, no PMI, competitive rates — the benefit you earned, used right.",
    description: "VA loans are mortgage loans guaranteed by the U.S. Department of Veterans Affairs, available to active-duty service members, veterans, and eligible surviving spouses. The terms are strong: zero down payment, no private mortgage insurance, competitive interest rates, and flexible qualification standards. If you've served, this is a benefit you've earned and we'll make sure you use it to its full advantage.",
    icon: "concentric",
    seo: {
      title: "VA Loans Portland Oregon | Zero Down | The Lindley Team",
      description: "VA home loans in Portland with zero down payment and no PMI. Expert guidance for veterans and active-duty service members. Licensed in OR/WA.",
      keywords: ["VA loan Portland", "VA mortgage Oregon", "veteran home loan Portland", "zero down mortgage Oregon", "VA loan requirements"],
      aeoQuestion: "How do VA loans work in Oregon?",
    },
    heroImage: "/img/illustration-portland.webp",
    whoFor: ["Active-duty military", "Veterans with eligible discharge", "National Guard and Reserve members", "Eligible surviving spouses"],
    requirements: [
      { label: "Eligibility", value: "Certificate of Eligibility (COE) from VA" },
      { label: "Down Payment", value: "0% — zero down" },
      { label: "Credit Score", value: "No VA minimum (most lenders: 580-620)" },
      { label: "Funding Fee", value: "1.25-3.3% (waived for disabled vets)" },
      { label: "Occupancy", value: "Primary residence only" },
    ],
    pros: ["Zero down payment", "No PMI ever", "Competitive rates below conventional", "No prepayment penalty", "Assumable by eligible buyers"],
    cons: ["Funding fee (1.25-3.3%) unless exempt", "Primary residence only", "VA appraisal required with specific property standards", "Not all lenders have VA experience"],
    process: [
      { step: "01", title: "Eligibility Check", desc: "We help you obtain your Certificate of Eligibility (COE) and confirm your entitlement." },
      { step: "02", title: "Pre-Approval", desc: "VA-specific pre-approval with zero-down scenario analysis." },
      { step: "03", title: "VA Appraisal", desc: "VA appraisals have specific requirements — we know what to expect." },
      { step: "04", title: "Close", desc: "Zero down, no PMI. Your monthly payment starts and you're home." },
    ],
    faqs: [
      { q: "How do VA loans work?", a: "The VA doesn't lend money directly — they guarantee a portion of the loan, which lets lenders offer zero down payment and no PMI. You still get your mortgage from a lender like us, but the VA backing means better terms." },
      { q: "What is the VA funding fee?", a: "A one-time fee of 1.25-3.3% of the loan amount, depending on your down payment and whether it's your first VA loan. It can be rolled into the loan. Veterans with service-connected disabilities are exempt." },
      { q: "Can I use my VA benefit more than once?", a: "Yes. VA loan entitlement can be reused. If you've paid off a previous VA loan or sold the home, your full entitlement is typically restored." },
      { q: "Do VA loans have loan limits?", a: "For veterans with full entitlement, there are no loan limits — you can borrow as much as a lender will approve. Reduced entitlement borrowers may have county-based limits." },
    ],
  },
  {
    slug: "jumbo",
    name: "Jumbo Loans",
    shortName: "Jumbo",
    tagline: "Above conforming limits for Portland's premium properties — competitive rates even at $1M+.",
    description: "Jumbo loans exceed the conforming loan limits set by the Federal Housing Finance Agency. In the Portland metro area, any mortgage above the conforming limit requires a jumbo loan. These are common for buyers in neighborhoods like Dunthorpe, Lake Oswego, West Hills, and the Pearl District where home prices regularly exceed conforming limits.",
    icon: "squircle",
    seo: {
      title: "Jumbo Loans Portland Oregon | The Lindley Team",
      description: "Jumbo mortgage loans for Portland's premium properties. Competitive rates on loans above conforming limits. Expert guidance for high-value purchases.",
      keywords: ["jumbo loan Portland", "jumbo mortgage Oregon", "high value mortgage Portland", "Portland luxury home loan"],
      aeoQuestion: "What is a jumbo loan and do I need one in Portland?",
    },
    heroImage: "/img/home-buy.webp",
    whoFor: ["Buyers purchasing above conforming loan limits", "High-net-worth individuals", "Buyers in Portland's premium neighborhoods", "Self-employed professionals with strong financials"],
    requirements: [
      { label: "Credit Score", value: "700+ typically required" },
      { label: "Down Payment", value: "10-20% typical" },
      { label: "Reserves", value: "6-12 months of payments in liquid assets" },
      { label: "DTI Ratio", value: "Under 43% preferred" },
      { label: "Documentation", value: "Extensive — full asset documentation required" },
    ],
    pros: ["Finance Portland's highest-value properties", "Competitive rates available", "Various term options (15, 20, 30 year)", "Interest-only options available on some programs"],
    cons: ["Higher credit score and down payment requirements", "More extensive documentation", "Rates can be slightly higher than conforming", "Fewer lender options — we know which ones are competitive"],
    process: [
      { step: "01", title: "Financial Review", desc: "Jumbo qualification requires thorough financial documentation. We review everything upfront to avoid surprises." },
      { step: "02", title: "Lender Matching", desc: "Not all lenders offer competitive jumbo products. We match you with the best jumbo lender for your profile." },
      { step: "03", title: "Underwriting", desc: "Jumbo underwriting is more detailed. We prepare your file meticulously to ensure smooth approval." },
      { step: "04", title: "Close", desc: "Closing on a jumbo loan follows the same process — just bigger numbers." },
    ],
    faqs: [
      { q: "What is the jumbo loan limit in Portland?", a: "Any loan above the current conforming limit is considered jumbo. This limit is updated annually by the FHFA. We'll confirm the current limit for your specific county during our initial conversation." },
      { q: "Are jumbo loan rates higher?", a: "Historically yes, but the gap has narrowed significantly. In some cases, jumbo rates are actually competitive with or even below conforming rates. It depends on your credit profile and down payment." },
      { q: "Can I get a jumbo loan with less than 20% down?", a: "Some programs allow 10-15% down on jumbo loans, but you'll likely pay a higher rate. With 20%+ down, you'll generally see stronger pricing and avoid the extra costs that come with a smaller down payment." },
    ],
  },
  {
    slug: "cash-out",
    name: "Cash-Out Refinance",
    shortName: "Cash-Out",
    tagline: "Turn your home equity into capital — consolidate debt, fund renovations, or invest.",
    description: "A cash-out refinance replaces your existing mortgage with a larger one, and you receive the difference in cash. If your home is worth $600,000 and you owe $350,000, you have $250,000 in equity. A cash-out refi lets you tap into that equity for home improvements, debt consolidation, investments, or any other purpose — at mortgage rates that are typically far lower than credit cards, personal loans, or HELOCs.",
    icon: "hexagon",
    seo: {
      title: "Cash-Out Refinance Portland | Tap Your Equity | The Lindley Team",
      description: "Cash-out refinance in Portland. Turn your home equity into capital for renovations, debt consolidation, or investment. Licensed in OR/WA.",
      keywords: ["cash out refinance Portland", "home equity cash out Oregon", "cash out refi Portland", "tap home equity Oregon"],
      aeoQuestion: "How much equity can I cash out of my home?",
    },
    heroImage: "/img/home-refinance.webp",
    whoFor: ["Homeowners with significant equity built up", "Those consolidating high-interest debt", "Homeowners funding major renovations", "Real estate investors leveraging equity for new purchases"],
    requirements: [
      { label: "Equity", value: "Must retain 20% equity after cash-out (conventional)" },
      { label: "Credit Score", value: "620+ (conventional), 580+ (FHA)" },
      { label: "DTI Ratio", value: "Under 50%" },
      { label: "Seasoning", value: "6+ months since last transaction" },
      { label: "LTV", value: "Up to 80% (conventional), 85% (FHA)" },
    ],
    pros: ["Lower rates than credit cards, personal loans, or HELOCs", "Tax-deductible interest if used for home improvements", "Single monthly payment replaces multiple debts", "No restrictions on how you use the cash"],
    cons: ["Increases your mortgage balance", "Closing costs of 2-3%", "Resets amortization if you extend the term", "Your home is the collateral — defaulting risks foreclosure"],
    process: [
      { step: "01", title: "Equity Analysis", desc: "We estimate your home's current value and calculate how much cash you can access while maintaining 20% equity." },
      { step: "02", title: "Purpose Review", desc: "We discuss what the cash is for and whether a cash-out refi is the best tool vs. HELOC or other options." },
      { step: "03", title: "Rate & Structure", desc: "We match your cash-out amount and term to the right Movement program and structure it for the strongest pricing you qualify for." },
      { step: "04", title: "Close & Fund", desc: "After closing, you typically receive your cash within 3 business days." },
    ],
    faqs: [
      { q: "How much can I cash out?", a: "On a conventional cash-out refinance, you can borrow up to 80% of your home's current value. If your home is worth $600,000, you can have a total loan of $480,000. Subtract what you currently owe, and the rest is your cash." },
      { q: "Is a cash-out refinance better than a HELOC?", a: "It depends. Cash-out refi gives you a fixed rate and a single payment. HELOC gives you a revolving credit line at a variable rate. We cover HELOCs on a separate page and can help you compare both options." },
      { q: "Do I pay taxes on cash-out refinance money?", a: "No — cash from a refinance is not taxable income because it's borrowed money, not earned income. However, if you use the funds for home improvements, the interest may be tax-deductible." },
    ],
  },
  {
    slug: "heloc",
    name: "HELOC",
    shortName: "HELOC",
    tagline: "A flexible credit line secured by your home — draw what you need, when you need it.",
    description: "A Home Equity Line of Credit (HELOC) works like a credit card secured by your home. You're approved for a maximum credit limit based on your equity, and you can draw from it as needed during the draw period (typically 10 years). You only pay interest on what you borrow. HELOCs are ideal for ongoing expenses like home renovations, education costs, or as an emergency fund — situations where you don't need all the money at once.",
    icon: "ellipse",
    seo: {
      title: "HELOC Portland Oregon | Home Equity Line of Credit | The Lindley Team",
      description: "HELOC in Portland — flexible home equity credit line. Draw what you need, pay interest only on what you use. Licensed in OR/WA.",
      keywords: ["HELOC Portland", "home equity line of credit Oregon", "HELOC rates Portland", "HELOC vs cash out refinance"],
      aeoQuestion: "How does a HELOC work and should I get one?",
    },
    heroImage: "/img/home-refinance.webp",
    whoFor: ["Homeowners funding phased renovations", "Those wanting a financial safety net", "Homeowners with ongoing large expenses", "Those who prefer flexible borrowing over lump sum"],
    requirements: [
      { label: "Equity", value: "15-20%+ equity in your home" },
      { label: "Credit Score", value: "680+ for stronger pricing" },
      { label: "DTI Ratio", value: "Under 43% typically" },
      { label: "Draw Period", value: "5-10 years" },
      { label: "Repayment Period", value: "10-20 years after draw period ends" },
    ],
    pros: ["Only pay interest on what you draw", "Flexible — use and repay as needed", "Lower rates than credit cards or personal loans", "Interest may be tax-deductible for home improvements"],
    cons: ["Variable interest rates can increase", "Your home secures the debt", "Draw period ends — then full repayment begins", "Can tempt over-borrowing if not disciplined"],
    process: [
      { step: "01", title: "Equity & Needs Assessment", desc: "We determine your available equity and discuss your borrowing needs to confirm HELOC is the right fit." },
      { step: "02", title: "Application & Appraisal", desc: "We apply with lenders offering the best HELOC terms. Your home is appraised to determine the credit limit." },
      { step: "03", title: "Approval & Access", desc: "Once approved, you receive checkbook or card access to your credit line." },
      { step: "04", title: "Draw & Repay", desc: "Use funds as needed during the draw period. Interest-only payments during draw; principal + interest during repayment." },
    ],
    faqs: [
      { q: "HELOC vs. cash-out refinance — which should I choose?", a: "HELOC if you need flexible, ongoing access to funds and want to keep your current mortgage intact. Cash-out refi if you want a lump sum at a fixed rate and are okay replacing your existing mortgage." },
      { q: "Are HELOC rates fixed or variable?", a: "Most HELOCs have variable rates tied to the prime rate. Some lenders offer fixed-rate options or the ability to lock portions of your balance at a fixed rate." },
      { q: "Can I lose my home with a HELOC?", a: "Yes — a HELOC is secured by your home. If you default on payments, the lender can foreclose. This is why we emphasize only borrowing what you can comfortably repay." },
    ],
  },
  {
    slug: "investment",
    name: "Investment Property Loans",
    shortName: "Investment",
    tagline: "Build wealth through Portland real estate — we handle the unique qualification requirements.",
    description: "Investment property loans finance properties you won't live in — rentals, flips, or multi-unit buildings. They come with different rules than primary residence loans: higher down payments, higher rates, and stricter qualification. But Portland's rental market makes investment properties a strong wealth-building strategy when financed correctly. We work with investors at every level, from first-time landlords buying a duplex to experienced investors scaling their portfolio.",
    icon: "diamond",
    seo: {
      title: "Investment Property Loans Portland | The Lindley Team",
      description: "Investment property financing in Portland. DSCR loans, conventional investment mortgages, and portfolio strategies. Build wealth through Oregon real estate.",
      keywords: ["investment property loan Portland", "rental property mortgage Oregon", "DSCR loan Portland", "Portland real estate investor financing"],
      aeoQuestion: "How do I finance an investment property in Portland?",
    },
    heroImage: "/img/illustration-portland.webp",
    whoFor: ["First-time rental property buyers", "Experienced investors scaling their portfolio", "House flippers needing purchase + rehab financing", "Buyers of multi-unit properties (2-4 units)"],
    requirements: [
      { label: "Down Payment", value: "15-25% depending on property type" },
      { label: "Credit Score", value: "680+ for stronger pricing" },
      { label: "Reserves", value: "6 months of payments per property" },
      { label: "DSCR Option", value: "Qualify on rental income, not personal income" },
      { label: "Experience", value: "Some programs require prior landlord experience" },
    ],
    pros: ["Build long-term wealth through appreciation and cash flow", "Rental income can cover mortgage payments", "DSCR loans let you qualify on property income, not personal income", "Tax benefits: depreciation, expense deductions, 1031 exchanges"],
    cons: ["Higher down payments and rates than primary residence", "Landlord responsibilities and vacancy risk", "More complex qualification", "Each property adds to your debt load"],
    process: [
      { step: "01", title: "Strategy Session", desc: "We discuss your investment goals, target returns, and portfolio strategy. First property or tenth — the approach is different." },
      { step: "02", title: "Product Matching", desc: "Conventional, DSCR, portfolio — we match the right loan product to your investment strategy." },
      { step: "03", title: "Analysis & Approval", desc: "We underwrite the deal, analyze cash flow projections, and secure approval." },
      { step: "04", title: "Close & Cash Flow", desc: "You close, place tenants, and start building wealth." },
    ],
    faqs: [
      { q: "How much do I need to put down on an investment property?", a: "Typically 15% for a single-family rental and 20-25% for multi-unit or DSCR loans. House hacking (living in one unit of a multi-unit) lets you use primary residence down payments as low as 3.5% (FHA)." },
      { q: "What is a DSCR loan?", a: "A Debt Service Coverage Ratio (DSCR) loan qualifies you based on the property's rental income rather than your personal income. If the rent covers 1.0-1.25x the mortgage payment, you can qualify regardless of your W2 income. Great for self-employed investors or those with multiple properties." },
      { q: "Can I use rental income to qualify?", a: "Yes. On conventional loans, we can use 75% of documented rental income. On DSCR loans, the property's income is the primary qualification factor." },
    ],
  },
  {
    slug: "reverse-mortgage",
    name: "Reverse Mortgage",
    shortName: "Reverse",
    tagline: "A loan against your home's equity, with no required monthly payments — for the right situation, for homeowners 62 and older.",
    description: "A reverse mortgage (formally a Home Equity Conversion Mortgage or HECM) is a real loan, not a giveaway: it lets homeowners aged 62+ borrow against their home equity without making monthly mortgage payments, but interest still accrues, you're still responsible for property taxes and insurance, and the balance comes due when you sell, move out, or pass away. It's not the right fit for everyone. For the right situation — supplementing retirement income, paying off an existing mortgage payment, or funding aging-in-place work — it can be a genuinely useful tool. HUD-approved counseling is required before you apply, and we'll walk you through the honest tradeoffs, not just the upside.",
    icon: "split-circle",
    seo: {
      title: "Reverse Mortgage Portland Oregon | HECM | The Lindley Team",
      description: "Reverse mortgages (HECM) in Portland for homeowners 62+. Honest guidance on the real tradeoffs — not just the upside. Not a government agency; HUD-approved counseling required.",
      keywords: ["reverse mortgage Portland", "HECM Oregon", "reverse mortgage 62+", "Portland reverse mortgage lender"],
      aeoQuestion: "How does a reverse mortgage work in Oregon?",
    },
    heroImage: "/img/illustration-portland.webp",
    whoFor: ["Homeowners 62+ with significant home equity", "Retirees who want to eliminate monthly mortgage payments", "Seniors needing funds for healthcare or aging-in-place modifications", "Homeowners who want to supplement retirement income"],
    requirements: [
      { label: "Age", value: "62+ (youngest borrower)" },
      { label: "Equity", value: "Significant equity — typically 50%+" },
      { label: "Occupancy", value: "Must be primary residence" },
      { label: "Counseling", value: "HUD-approved counseling required" },
      { label: "Property", value: "Single-family, 2-4 unit, condo, or manufactured home" },
      { label: "Note", value: "This is not a government agency. Movement Mortgage is not affiliated with or endorsed by HUD, FHA, or any government entity." },
    ],
    pros: ["No required monthly mortgage payments (interest still accrues)", "Stay in your home", "Non-recourse — you'll never owe more than the home's value", "Multiple payout options (lump sum, line of credit, monthly payments)", "Proceeds are generally tax-free (confirm with a tax advisor)"],
    cons: ["Loan balance grows over time as interest accrues", "Reduces inheritance for heirs", "Upfront costs can be significant", "Must maintain the home and pay taxes/insurance", "Moving out triggers repayment"],
    process: [
      { step: "01", title: "Education & Counseling", desc: "We explain how reverse mortgages work honestly — pros AND cons. HUD-approved counseling is required before application." },
      { step: "02", title: "Application & Appraisal", desc: "We determine how much you can access based on age, home value, and current interest rates." },
      { step: "03", title: "Underwriting", desc: "Financial assessment ensures you can maintain the home, pay taxes, and maintain insurance." },
      { step: "04", title: "Close & Access Funds", desc: "Choose your payout option and start accessing your equity — with no monthly payment due." },
    ],
    faqs: [
      { q: "How does a reverse mortgage work?", a: "Instead of you paying the bank each month, the bank pays you — either as a lump sum, monthly payments, or a credit line. The loan balance (plus interest) is repaid when you sell, move out, or pass away. You retain ownership of the home the entire time." },
      { q: "Will I lose my home with a reverse mortgage?", a: "No. You retain full ownership. The loan becomes due only when you sell, move out permanently, or pass away. Your heirs can choose to repay the loan and keep the home, or sell it." },
      { q: "How much can I get from a reverse mortgage?", a: "It depends on your age, home value, and current interest rates. Generally, older borrowers with more equity and lower rates can access more. Our calculator can give you an estimate." },
      { q: "Are reverse mortgage proceeds taxable?", a: "No. Reverse mortgage funds are loan proceeds, not income, so they're not subject to income tax. They also don't affect Social Security benefits (though they may affect Medicaid — consult a financial advisor)." },
    ],
  },
  {
    slug: "conventional",
    name: "Conventional Loans",
    shortName: "Conventional",
    tagline: "The loan most Portland buyers end up with — and usually the right call. As little as 3% down with solid credit.",
    description: "A conventional loan is a mortgage that isn't backed by a government agency — it follows Fannie Mae and Freddie Mac guidelines instead. For borrowers with a 620+ credit score, it's often the more straightforward route to a Portland home: down payments start at 3%, mortgage insurance drops off once you reach 20% equity, and the paperwork is lighter than FHA. The Lindley Team walks you through whether conventional beats FHA for your numbers — the answer depends on your credit score and down payment, and we'll show you both side by side.",
    icon: "circle",
    tag: "Most Common",
    seo: {
      title: "Conventional Home Loans Portland Oregon | 3% Down | The Lindley Team",
      description: "Conventional mortgage loans in Portland with as little as 3% down. We'll show you conventional vs. FHA side by side. Licensed OR & WA. NMLS #1367416 / #265974.",
      keywords: ["conventional loan Portland", "conventional mortgage Oregon", "3 percent down conventional", "conventional vs FHA Oregon", "Fannie Mae loan Portland"],
      aeoQuestion: "What is a conventional loan and how much do I need down in Oregon?",
    },
    heroImage: "/img/home-buy.webp",
    whoFor: [
      "Buyers with a 620+ credit score and steady income",
      "First-time buyers who qualify for 3% down conventional programs",
      "Move-up buyers with equity from a previous home",
      "Anyone who wants mortgage insurance that eventually goes away",
      "Buyers comparing conventional vs. FHA and wanting real numbers on both",
    ],
    requirements: [
      { label: "Credit Score", value: "620+ (best pricing at 740+)" },
      { label: "Down Payment", value: "3% first-time buyers; 5% standard" },
      { label: "DTI Ratio", value: "Typically under 45-50%" },
      { label: "Loan Limit", value: "Conforming limit applies (higher = jumbo)" },
      { label: "Mortgage Insurance", value: "Required under 20% down; removable at 20% equity" },
    ],
    pros: [
      "PMI cancels once you hit 20% equity — unlike FHA's mortgage insurance",
      "Lower total cost than FHA for borrowers with good credit",
      "Works for primary homes, second homes, and investment properties",
      "Fewer property condition requirements than FHA appraisals",
      "Flexible terms: 15, 20, or 30 years, fixed or adjustable",
    ],
    cons: [
      "Tighter credit requirements than FHA",
      "Pricing is credit-score sensitive — lower scores pay more",
      "PMI is required until you reach 20% equity",
      "Conforming loan limits cap how much you can borrow before jumbo territory",
    ],
    process: [
      { step: "01", title: "Credit & Numbers Review", desc: "We look at your credit, income, and savings, and show you conventional vs. FHA side by side. One is usually clearly better for you." },
      { step: "02", title: "Pre-Approval", desc: "We turn around a real answer in 24-48 hours. If you qualify, you get a letter Portland sellers take seriously." },
      { step: "03", title: "Rate & Structure", desc: "We lock your rate and pick the term and PMI structure that costs you the least over the years you'll actually own the home." },
      { step: "04", title: "Close", desc: "We manage underwriting, appraisal, and closing. You show up and sign." },
    ],
    faqs: [
      { q: "What credit score do I need for a conventional loan?", a: "620 is the minimum, but pricing improves meaningfully as your score climbs — 740+ gets the strongest pricing. If you're in the 620-680 range, we'll compare conventional against FHA, because FHA sometimes wins on monthly payment at lower scores." },
      { q: "Is 3% down really possible on a conventional loan?", a: "Yes — first-time buyer conventional programs allow 3% down. On a $500,000 Portland home, that's $15,000. You'll pay PMI until you reach 20% equity, but unlike FHA, it eventually goes away without refinancing." },
      { q: "Conventional vs. FHA — which is better?", a: "It depends almost entirely on your credit score and down payment. Strong credit usually favors conventional (cheaper PMI that cancels). Lower scores or thin savings can favor FHA. We run both and show you the actual monthly numbers — it takes about ten minutes." },
      { q: "What is PMI and how do I get rid of it?", a: "Private mortgage insurance protects the lender when you put down less than 20%. It's removable: once you reach 20% equity through payments or appreciation, you can request cancellation, and at 22% it drops automatically. That's a major advantage over FHA's insurance, which usually lasts the life of the loan." },
      { q: "What's the conforming loan limit in Portland?", a: "Conforming limits adjust annually and vary by county. If your loan amount is above the limit for Multnomah, Washington, or Clackamas County, you're in jumbo territory — which we also handle. We'll tell you which side of the line you're on in the first call." },
    ],
  },
  {
    slug: "usda",
    name: "USDA Loans",
    shortName: "USDA",
    tagline: "Zero down for homes outside the city core — more of the Portland metro qualifies than you'd guess.",
    description: "A USDA loan is a zero-down mortgage backed by the U.S. Department of Agriculture for homes in eligible rural and suburban areas. 'Rural' is more generous than it sounds: communities on the edges of the Portland metro — parts of Yamhill, Columbia, and Clark County, and towns like Newberg, Estacada, and Battle Ground — often qualify. If you're open to living outside the city core, USDA can put you in a home with no down payment and competitive rates. We check address eligibility in minutes.",
    icon: "hexagon",
    seo: {
      title: "USDA Home Loans Oregon | Zero Down | The Lindley Team",
      description: "USDA loans near Portland: zero down payment for eligible areas like Newberg, Estacada, and Battle Ground. We check eligibility in minutes. NMLS #1367416 / #265974.",
      keywords: ["USDA loan Oregon", "zero down home loan Oregon", "USDA eligible areas Portland", "USDA loan Newberg", "rural development loan Washington state"],
      aeoQuestion: "Can I get a zero-down USDA loan near Portland Oregon?",
    },
    heroImage: "/img/illustration-portland.webp",
    whoFor: [
      "Buyers open to living outside the Portland city core",
      "Households with little or no down payment saved",
      "Moderate-income families (USDA has income limits by county)",
      "First-time buyers priced out of close-in neighborhoods",
      "Anyone eyeing Newberg, Estacada, Battle Ground, or similar communities",
    ],
    requirements: [
      { label: "Down Payment", value: "0%" },
      { label: "Location", value: "USDA-eligible area (we check your address)" },
      { label: "Income", value: "Under USDA limits for your county and household size" },
      { label: "Credit Score", value: "640+ for streamlined approval" },
      { label: "Occupancy", value: "Primary residence only" },
    ],
    pros: [
      "True zero down payment",
      "Competitive rates — often below conventional",
      "Lower mortgage insurance cost than FHA",
      "Closing costs can be rolled in or covered by seller credits",
      "Puts real homeownership in reach without years of saving",
    ],
    cons: [
      "Only works in USDA-eligible areas — close-in Portland doesn't qualify",
      "Household income limits apply",
      "Primary residences only — no investment properties",
      "Processing adds a USDA review step, so closings run slightly longer",
    ],
    process: [
      { step: "01", title: "Eligibility Check", desc: "We check the address (or the towns you're considering) against the USDA map and confirm your income fits the county limits. Takes minutes." },
      { step: "02", title: "Pre-Approval", desc: "Standard pre-approval with the zero-down structure priced in, so you know your real monthly payment." },
      { step: "03", title: "USDA Review", desc: "After underwriting, USDA gives its sign-off. We build the extra days into your offer timeline so nothing surprises you." },
      { step: "04", title: "Close", desc: "Zero down at the closing table. Keep your savings for the house itself." },
    ],
    faqs: [
      { q: "What areas near Portland qualify for USDA loans?", a: "Eligibility follows USDA's rural map, which includes much more of the metro edge than people expect — parts of Yamhill, Columbia, Marion, and Clark County, and towns like Newberg, Estacada, Sandy, Molalla, and Battle Ground. Send us an address and we'll check it same-day." },
      { q: "Is USDA really zero down?", a: "Yes — 100% financing, no down payment. You'll still have closing costs, but those can often be covered through seller credits or rolled into the loan when the appraisal supports it." },
      { q: "What are the USDA income limits?", a: "Limits vary by county and household size, and they're higher than most people assume — many two-income households still qualify. We'll check your numbers against the current limits in the first conversation." },
      { q: "USDA vs. FHA — which should I pick?", a: "If the home is in an eligible area and your income fits, USDA usually wins: zero down beats 3.5% down, and USDA's monthly insurance cost is lower. If the address doesn't qualify, FHA is the fallback. We'll price both." },
      { q: "How long does a USDA loan take to close?", a: "Plan on 30-45 days. USDA adds its own review after underwriting, which can add a few days to a couple of weeks depending on their queue. We track it and keep your agent in the loop." },
    ],
  },
  {
    slug: "new-construction",
    name: "New Construction Loans",
    shortName: "Construction",
    tagline: "Building or buying new? The financing has more moving parts — David has spent 20 years keeping them in order.",
    description: "New construction financing covers homes that don't exist yet — whether you're buying from a builder or building on your own lot. The timing is different from a standard purchase: rate locks have to survive a build schedule, draws have to match construction milestones, and the appraisal happens on a house that's still on paper. David has financed new builds for two decades and knows how to structure the loan so a delayed drywall delivery doesn't blow up your rate lock.",
    icon: "square",
    seo: {
      title: "New Construction Loans Portland Oregon | The Lindley Team",
      description: "Construction and new-build home financing in Portland. Extended rate locks, builder coordination, construction-to-permanent loans. NMLS #265974 / #1367416.",
      keywords: ["construction loan Portland", "new construction financing Oregon", "construction to permanent loan", "new build mortgage Portland", "builder financing Oregon"],
      aeoQuestion: "How do construction loans work in Oregon?",
    },
    heroImage: "/img/illustration-portland.webp",
    whoFor: [
      "Buyers purchasing a to-be-built home from a builder",
      "Homeowners building on their own lot",
      "Buyers in new developments (Happy Valley, Ridgefield, Bethany, and similar)",
      "Anyone whose closing date depends on a construction schedule",
      "Move-up buyers coordinating a build with the sale of a current home",
    ],
    requirements: [
      { label: "Credit Score", value: "660+ typical for construction products" },
      { label: "Down Payment", value: "Varies by structure; builder deals can be as low as standard purchase" },
      { label: "Documentation", value: "Builder contract, plans & specs, or lot ownership" },
      { label: "Rate Lock", value: "Extended locks available to cover the build timeline" },
      { label: "Appraisal", value: "Based on plans and comparable completed homes" },
    ],
    pros: [
      "Brand-new home, no deferred maintenance, modern efficiency codes",
      "Extended rate locks protect you through the build",
      "Construction-to-permanent options mean one closing, not two",
      "Builder incentives can often be paired with your financing",
      "We coordinate directly with the builder so deadlines don't slip past anyone",
    ],
    cons: [
      "Build timelines move — financing has to be structured to absorb delays",
      "Extended rate locks can carry a cost",
      "Custom builds on your own lot require more documentation and reserves",
      "The home you tour is a model, not the one you're buying — details live in the specs",
    ],
    process: [
      { step: "01", title: "Structure the Deal", desc: "Builder purchase or own-lot build? One closing or two? We map the financing to the actual construction timeline before you sign anything." },
      { step: "02", title: "Approval & Rate Strategy", desc: "Full approval up front, plus a rate-lock plan that covers the build window — including what happens if the schedule slips." },
      { step: "03", title: "Build Period", desc: "We track milestones with the builder and keep your file current, so a six-month build doesn't mean re-documenting your life at the end." },
      { step: "04", title: "Final Appraisal & Close", desc: "The finished home gets appraised, we confirm final numbers, and you close on schedule." },
    ],
    faqs: [
      { q: "How is a construction loan different from a regular mortgage?", a: "A regular mortgage funds a finished house in one transaction. Construction financing has to survive a build: extended rate locks, milestone-based timing, and an appraisal based on plans. Structured well, it feels almost like a normal purchase. Structured badly, a two-week delay can cost you your rate. That's the part we manage." },
      { q: "Should I use the builder's preferred lender?", a: "Compare. Builder lenders sometimes offer real incentives, but their pricing isn't automatically better — and you're allowed to shop. Bring us the builder's offer and we'll tell you honestly whether to take it. Sometimes the answer is yes." },
      { q: "What happens to my rate lock if construction is delayed?", a: "This is the big risk in new construction, and it's manageable: extended locks, lock extensions, and float-down options all exist. We build the rate strategy around the builder's realistic timeline — not the optimistic one in the brochure." },
      { q: "Can I build on my own land?", a: "Yes. Own-lot construction uses a construction-to-permanent loan: one closing that covers the build and converts to a standard mortgage at completion. It requires more documentation (plans, specs, builder contract) and we'll walk you through the list." },
      { q: "Do new construction homes need an inspection?", a: "Get one anyway. New doesn't mean flawless, and a pre-drywall inspection plus a final walk-through inspection are cheap insurance. Your financing doesn't require it, but we'd tell you to do it regardless — it's your money." },
    ],
  },
  {
    slug: "bank-statement",
    name: "Bank Statement Loans",
    shortName: "Self-Employed",
    tagline: "Self-employed and your tax returns undersell you? Your bank statements can qualify you instead.",
    description: "A bank statement loan qualifies you using 12-24 months of business or personal bank deposits instead of tax returns. If you're self-employed, a contractor, or a business owner, you probably write off everything you legally can — great for your tax bill, terrible for your debt-to-income ratio on paper. Bank statement programs look at what your business actually deposits, which is usually a much fairer picture. Portland runs on small businesses and 1099 income; this is the loan built for how you actually get paid.",
    icon: "diamond",
    tag: "Self-Employed",
    seo: {
      title: "Bank Statement Loans Portland | Self-Employed Mortgage Oregon | The Lindley Team",
      description: "Self-employed mortgage loans in Portland using bank statements instead of tax returns. 1099, contractor, and business-owner friendly. NMLS #265974 / #1367416.",
      keywords: ["bank statement loan Oregon", "self employed mortgage Portland", "1099 home loan Oregon", "no tax return mortgage", "business owner mortgage Portland"],
      aeoQuestion: "How can I get a mortgage if I'm self-employed and write off most of my income?",
    },
    heroImage: "/img/home-refinance.webp",
    whoFor: [
      "Self-employed borrowers whose tax returns undersell their real income",
      "1099 contractors, freelancers, and gig-economy earners",
      "Small business owners with strong deposits and aggressive write-offs",
      "Real estate agents, tradespeople, and consultants",
      "Anyone told 'no' by a lender who only looked at their 1040",
    ],
    requirements: [
      { label: "Bank Statements", value: "12-24 months, business or personal" },
      { label: "Self-Employment", value: "Typically 2+ years in the business" },
      { label: "Credit Score", value: "660+ for most programs" },
      { label: "Down Payment", value: "Typically 10-20%" },
      { label: "Reserves", value: "A few months of payments in savings" },
    ],
    pros: [
      "Qualify on real cash flow, not your tax strategy",
      "Keep your write-offs — no amending returns to look better on paper",
      "Works for purchases and refinances",
      "Faster documentation than rebuilding two years of tax narratives",
      "Pricing has gotten far more competitive as these programs matured",
    ],
    cons: [
      "Rates run somewhat higher than conventional",
      "Larger down payment than a 3-5% conventional loan",
      "Deposit history needs to be reasonably consistent",
      "Not every lender offers these — program quality varies a lot",
    ],
    process: [
      { step: "01", title: "Deposit Review", desc: "Send 12-24 months of statements. We calculate your qualifying income the way the program will, so you know your real budget before you shop." },
      { step: "02", title: "Program Match", desc: "Bank statement, or would full documentation actually price better for you? We check both — sometimes the boring answer wins." },
      { step: "03", title: "Approval", desc: "Underwriting reviews deposits instead of tax returns. We package the file so your business's story is obvious on the first pass." },
      { step: "04", title: "Close", desc: "Same closing as any other loan. Your CPA never has to unwind a single write-off." },
    ],
    faqs: [
      { q: "How do bank statement loans work?", a: "Instead of tax returns, the lender reviews 12-24 months of bank deposits and applies an expense factor to estimate your real income. If your business deposits $30k a month but your 1040 shows $60k a year after write-offs, this is the difference between qualifying and not." },
      { q: "Do I need to stop writing things off to buy a house?", a: "No — that's exactly what this program avoids. Conventional wisdom says self-employed buyers should show more income on their taxes for two years before buying. A bank statement loan skips that: keep your tax strategy, qualify on deposits." },
      { q: "Are the rates higher on a bank statement loan?", a: "Somewhat, yes — you're paying for documentation flexibility. But the honest comparison isn't bank-statement vs. conventional rates; it's bank-statement vs. not qualifying at all, or vs. two years of overpaying taxes to look better on paper. We'll show you the real math." },
      { q: "Can I refinance with a bank statement loan?", a: "Yes — both rate-and-term and cash-out refinances work with bank statement documentation. If you bought with a higher-rate program and your deposits have grown, refinancing into better terms is a common move." },
      { q: "What if my deposits are irregular?", a: "Seasonal and lumpy income is normal for small businesses, and underwriters know it. Programs average your deposits over 12-24 months precisely for this reason. Big one-time transfers need explaining, but a busy summer and slow January won't sink you." },
    ],
  },
  {
    slug: "dscr",
    name: "DSCR Investor Loans",
    shortName: "DSCR",
    tagline: "The property qualifies, not your paycheck. Rental cash flow is the whole application.",
    description: "A DSCR (debt service coverage ratio) loan qualifies an investment property on its own rental income — no tax returns, no W2s, no debt-to-income calculation on you personally. If the rent covers the mortgage payment, the deal can stand on its own. For Portland investors scaling past their second or third property, DSCR is usually the unlock: conventional guidelines start fighting you as your portfolio grows, while DSCR just asks whether each property pencils.",
    icon: "concentric",
    tag: "Investors",
    seo: {
      title: "DSCR Loans Portland Oregon | Investment Property Financing | The Lindley Team",
      description: "DSCR investor loans in Portland — qualify on rental income, not personal income. Built for scaling portfolios. NMLS #265974 / #1367416.",
      keywords: ["DSCR loan Oregon", "DSCR loan Portland", "investment property loan no tax returns", "rental property financing Oregon", "portfolio investor loan Portland"],
      aeoQuestion: "What is a DSCR loan and how do I qualify for one in Oregon?",
    },
    heroImage: "/img/illustration-portland.webp",
    whoFor: [
      "Investors buying rental property without wanting personal income scrutiny",
      "Portfolio builders hitting conventional's property-count friction",
      "Self-employed investors whose tax returns don't reflect buying power",
      "Out-of-state investors adding Portland or Vancouver rentals",
      "Short-term rental operators (program-dependent — ask us)",
    ],
    requirements: [
      { label: "DSCR", value: "Rent ÷ payment ≥ 1.0 typical; best terms at 1.25+" },
      { label: "Down Payment", value: "Typically 20-25%" },
      { label: "Credit Score", value: "660+ (700+ improves pricing meaningfully)" },
      { label: "Property", value: "1-4 unit residential investment" },
      { label: "Personal Income Docs", value: "None — no tax returns, no W2s, no DTI" },
    ],
    pros: [
      "No personal income documentation at all",
      "Scales with your portfolio instead of fighting it",
      "Fast underwriting — the property is the whole file",
      "Works in an LLC on most programs",
      "Cash-out DSCR refinances let you recycle equity into the next purchase",
    ],
    cons: [
      "Higher rates than owner-occupied conventional loans",
      "20-25% down is the standard entry",
      "Properties that don't cash flow don't qualify — that's the whole test",
      "Prepayment penalties are common on the best-priced programs (we'll flag them)",
    ],
    process: [
      { step: "01", title: "Run the Ratio", desc: "Address plus expected rent — that's all we need to tell you if the deal works. Market rent comes from the appraiser's rent schedule if the unit isn't leased yet." },
      { step: "02", title: "Structure", desc: "Purchase or cash-out, personal name or LLC, prepay penalty trade-offs — we structure it around your portfolio plan, not just this one deal." },
      { step: "03", title: "Appraisal & Rent Schedule", desc: "The appraisal establishes value and market rent. Underwriting checks the ratio. Nobody asks for your tax returns." },
      { step: "04", title: "Close & Repeat", desc: "Close, place the tenant, and when the equity's grown — a cash-out DSCR refi funds the next one. That's the flywheel." },
    ],
    faqs: [
      { q: "What is a DSCR loan?", a: "A loan where the investment property qualifies on its own cash flow. DSCR = monthly rent ÷ monthly payment (principal, interest, taxes, insurance, HOA). At 1.0 the rent covers the payment; most programs want 1.0-1.25. Your personal income never enters the equation." },
      { q: "Can I close in an LLC?", a: "On most DSCR programs, yes — which conventional loans generally don't allow. If you're building a portfolio with liability separation, this is one of DSCR's biggest practical advantages." },
      { q: "What if the property isn't rented yet?", a: "The appraiser completes a market rent schedule (Form 1007) as part of the appraisal, and the program uses that figure. Vacant properties finance fine as long as market rent supports the payment." },
      { q: "Do DSCR loans work for short-term rentals?", a: "Some programs count STR income (often using 12-month revenue history or a projection tool), others only use long-term market rent. If your Airbnb math is the whole deal, tell us up front and we'll match you to a program that counts it." },
      { q: "DSCR vs. conventional investment loan — which is better?", a: "If you qualify conventionally and it's your first or second rental, conventional usually prices better. DSCR wins when your tax returns are complicated, your portfolio is growing, or you want the LLC. We'll run both and tell you which one this deal wants." },
    ],
  },
  {
    slug: "down-payment-assistance",
    name: "Down Payment Assistance",
    shortName: "DPA",
    tagline: "Oregon and Washington will help with your down payment. Most buyers never even check.",
    description: "Down payment assistance (DPA) programs offer grants, forgivable loans, and low-interest second loans that cover part or all of your down payment and closing costs. Oregon Housing and Community Services (OHCS), the Washington State Housing Finance Commission, and various city and county programs all run active assistance — and eligibility reaches further into the middle class than most people assume. We keep current on what's funded, what's waitlisted, and what stacks with which loan types, because this landscape changes constantly.",
    icon: "star",
    seo: {
      title: "Down Payment Assistance Oregon & Washington | OHCS Programs | The Lindley Team",
      description: "Oregon and Washington down payment assistance: OHCS programs, grants, and forgivable seconds explained. Find out what you qualify for. NMLS #1367416 / #265974.",
      keywords: ["down payment assistance Oregon", "OHCS down payment assistance", "first time buyer grants Portland", "Washington down payment assistance", "Oregon Bond loan program"],
      aeoQuestion: "What down payment assistance programs are available in Oregon and Washington?",
    },
    heroImage: "/img/home-buy.webp",
    whoFor: [
      "First-time buyers short on down payment, solid on income",
      "Buyers who assumed they need 20% down (almost nobody does)",
      "Moderate-income households within program limits",
      "Teachers, healthcare workers, and public employees (some programs favor them)",
      "Anyone whose only obstacle to buying is the cash at closing",
    ],
    requirements: [
      { label: "Income", value: "Program limits vary — many reach well into middle income" },
      { label: "Buyer Status", value: "Most (not all) target first-time buyers" },
      { label: "Education", value: "Homebuyer education course usually required" },
      { label: "Occupancy", value: "Primary residence" },
      { label: "Pairing", value: "Stacks with conventional, FHA, and other loan types" },
    ],
    pros: [
      "Real money toward down payment and closing costs — sometimes forgivable",
      "Stacks with 3%-down conventional or 3.5%-down FHA to shrink cash-to-close dramatically",
      "Some programs forgive entirely after you stay in the home a set number of years",
      "Income limits are higher than most buyers assume",
      "Turns 'a few more years of saving' into 'this year' for a lot of households",
    ],
    cons: [
      "Program funding comes and goes — timing matters",
      "Some assistance is a repayable second loan, not a grant (we'll be clear about which)",
      "Adds paperwork and sometimes a week or two to closing",
      "Income and purchase-price limits exclude some buyers and neighborhoods",
    ],
    process: [
      { step: "01", title: "Eligibility Scan", desc: "Income, household size, location, first-time status — we check you against every currently funded program in OR/WA, not just the famous ones." },
      { step: "02", title: "Stack & Structure", desc: "We pair the assistance with the right base loan and show you the real cash-to-close number. This is where the magic actually happens." },
      { step: "03", title: "Education Course", desc: "Most programs require a homebuyer education class — a few hours, online, genuinely useful. We'll point you to an approved one." },
      { step: "04", title: "Close", desc: "The assistance funds at closing alongside your loan. Your savings stay in your pocket for moving, furniture, and the surprises every house brings." },
    ],
    faqs: [
      { q: "What down payment assistance exists in Oregon?", a: "OHCS runs the state's flagship programs (including Oregon Bond Residential Loan options with cash assistance), and there are city and county programs on top — Portland Housing Bureau assistance among them. What's actually funded changes through the year, which is why we check live rather than working off last year's list." },
      { q: "Do I have to pay down payment assistance back?", a: "Depends on the program. Some are grants (never repaid), some are forgivable seconds (forgiven after you occupy the home a set number of years), and some are low-interest or deferred loans repaid when you sell or refinance. We'll tell you exactly which type you're getting before you commit." },
      { q: "What are the income limits for assistance in Oregon?", a: "They vary by program and county, and they're higher than most people expect — many programs serve households earning around or even above the area median income. Two-income households frequently still qualify. It costs nothing to check." },
      { q: "Can I combine assistance with an FHA or conventional loan?", a: "Yes — that's the standard play. Assistance covers some or all of the down payment on a 3% conventional or 3.5% FHA loan, which can shrink your cash-to-close to a fraction of what you feared. Stacking rules vary by program, and we handle that matching." },
      { q: "Does using assistance make my offer weaker?", a: "In practice, rarely. The assistance is approved up front and funds at closing like any other source. A clean pre-approval letter with a realistic timeline is what listing agents care about — and that part is on us, not the program." },
    ],
  },
];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find((s) => s.slug === slug);
}
